### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by Gunner62** [JessicaYeh/rom-exchange-web#39]
Hey! 
Great work on this app.
I am interested in making a discord bot using your API to track certain items things for my guild. I was wondering how quickly your scraper updates the values. I am hoping to make a discord bot that notifies us when certain low stock items are put on the exchange e.g. Mini/MVP cards. Do you think this would be possible using the API?
Thanks for the help

**Comment by bongikairu** [comment]
Disclaimer: I work for Poporing Life

If you're looking for the freshest data, SEA or Global, Poporing Life offers data at 3 hours interval or faster. You can manually pulled data using our API regularly and send a notification. You will find our API guide at the bottom of our website. Or if you just want it to work, we also have this notification feature at a price.

**Comment by JessicaYeh** [comment]
Hi Gunner,

The data is updated daily in the morning. There are plans (no ETA) for ROM Exchange to eventually have such a feature built-in, so it can send a notification to the destination of your choosing as soon as it detects an item that you are tracking has re-appeared. The data isn't refreshed quickly enough at the moment to accurately do that. I would prefer to have it be refreshing at least every hour, since some items on snap can disappear as quickly as 30 minutes after its listed, but most seem to be after 120 minutes.

**Comment by Gunner62** [comment]
Thanks for the response Jessica.
I think I will try to implement the idea I had with the Poporing Life tracker for now. Just out of curiosity, what kind of system would you need to refresh the exchange more quickly? Would you just need more instances of emulators to scrape data faster off the exchange?
